name: Build
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build --build-arg APP_KEY=base64:zdLJ3LKXIt6ujUTJudu+k/O88ndxDS1I9czpHEAFA5s= . -t funwithblade:${{ github.sha }}
      - name: Test
        run: docker run --rm funwithblade:${{ github.sha }} php artisan test